version: '2'
services:
  web:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"

    # Uncomment below when developing
    # tty: true
    # stdin_open: true
    # command: "--dev=xml,reload"

    volumes:
      - ./config:/etc/odoo
      - ./extra_addons:/mnt/extra_addons
      - ./third_party_addons:/mnt/third_party_addons
  db:
    image: postgres:12
    # ports:
    #   - "54321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
